Input                  = "resource/input.wkt"
Output                 = ""
Constraints            = "resource/constraints.wkt"
SimplificationType     = "dp"
Threshold              = 50.0
MinDist                = 20.0
RelaxDist              = 30.0
IsFeatureClass         = false
PlanarSelf             = true
NonPlanarSelf          = true
AvoidNewSelfIntersects = true
GeomRelation           = true
DistRelation           = true
SideRelation           = true
